services:
  app:
    build:
      context: .
    container_name: inventory_app
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: postgres
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - ./migrations:/migrations
      - ./pkg/uploads:/app/pkg/uploads
    networks:
      - inventory_network

  postgres:
    image: postgres:15
    container_name: inventory_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - inventory_network

volumes:
  postgres_data:
    driver: local

networks:
  inventory_network:
    driver: bridge
